### ISSUE TITLE
Issue with the CP/start handler

### ISSUE THREAD

**Issue by tomvlk** [teemann/currentcps#2]
Don't know if it's fixed. But we received the following exception:
`bad operand type for unary -: 'list'`

`Signal receiver 'teemann.currentcps' => player_cp thrown an exception!`
`Signal receiver 'teemann.currentcps' => player_start thrown an exception!`

I don't have a full stacktrace unfortunately, it can also be from your development machine, but I'm not sure. (from view of some of the logins, it seems to be a real live server).

**Comment by teemann** [comment]
Thank you for the report.
Should be fixed now.
