### ISSUE TITLE
PyPlanet 0.5.1 Update Issue with teemann.currentcps

### ISSUE THREAD

**Issue by hpD-orso** [teemann/currentcps#4]
yo teemann,
i have update my python to 3.6.3 and install pyplanet 0.5.1 and after the installation i have following errors with your pyplanet app teemann.currentcps:

WARNING  [default][pyplanet.core.instance] DEPRECATED: The usage of 'self.instan
ce.signal_manager' in apps is deprecated, use 'self.context.signals' instead!
WARNING  [default][pyplanet.core.instance]   File "C:\Users\Administrator\AppDat
a\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_f
orever
    self._run_once()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asynci
o\base_events.py", line 1426, in _run_once
    handle._run()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\asynci
o\events.py", line 127, in _run
    self._callback(*self._args)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pyplanet\core\instance.py", line 182, in _start
    await self.apps.start()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pyplanet\apps\apps.py", line 187, in start
    await app.on_start()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pyplanet\apps\contrib\teemann\currentcps\__init__.py", line 55, in on_st
art
    self.instance.signal_manager.listen(mp_signals.player.player_enter_spectator
_slot, self.player_enter_spec)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pyplanet\core\instance.py", line 108, in signal_manager
    logger.warning('\n'.join(traceback.format_stack(limit=7)))

Its possible to update your app?

bg
orso

**Comment by teemann** [comment]
Should be fixed now. I have uploaded the new version to pypi (pip install -U pyplanet_currentcps)
